/*
 * Omega Video Downloader Project Original (2026)
 * arslandaim-hub (GitHub.com/arslandaim-hub)
 * Licenced Under GPL-3.0+
*/
package com.arslandaim.omegavideodownloader

import android.content.Context
import android.net.Uri
import java.io.File
import java.io.FileOutputStream

object CookiesManager {
    private const val COOKIES_FILE_NAME = "cookies.txt"

    fun getCookiesPath(context: Context): String? {
        val file = File(context.filesDir, COOKIES_FILE_NAME)
        return if (file.exists()) file.absolutePath else null
    }

    fun importCookies(context: Context, uri: Uri): Boolean {
        return try {
            val contentResolver = context.contentResolver
            contentResolver.openInputStream(uri)?.use { input ->
                val outputFile = File(context.filesDir, COOKIES_FILE_NAME)
                FileOutputStream(outputFile).use { output ->
                    input.copyTo(output)
                }
            }
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    fun clearCookies(context: Context) {
        val file = File(context.filesDir, COOKIES_FILE_NAME)
        if (file.exists()) file.delete()
    }

    fun saveCookies(context: Context, cookies: String, domain: String) {
        try {
            val file = File(context.filesDir, COOKIES_FILE_NAME)
            val isNewFile = !file.exists()
            
            val stringBuilder = StringBuilder()
            if (isNewFile) {
                stringBuilder.append("# Netscape HTTP Cookie File\n")
                stringBuilder.append("# This file is generated by Omega Video Downloader\n\n")
            }
            
            val cookiePairs = cookies.split("; ")
            for (pair in cookiePairs) {
                if (pair.isBlank()) continue
                val parts = pair.split("=", limit = 2)
                if (parts.size == 2) {
                    val name = parts[0].trim()
                    val value = parts[1].trim()
                    val domainWithDot = if (domain.startsWith(".")) domain else ".$domain"
                    // domain, flag, path, secure, expiration, name, value
                    stringBuilder.append("$domainWithDot\tTRUE\t/\tTRUE\t0\t$name\t$value\n")
                }
            }
            
            FileOutputStream(file, true).use { output ->
                output.write(stringBuilder.toString().toByteArray())
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
